export default {
  'searchToRss.title': 'Search to RSS',
  'searchToRss.description':
    'Generate RSS feeds from search queries using AI providers.',
  'searchToRss.step.searchQuery': 'Search Query',
  'searchToRss.step.searchQuery.desc': 'Enter your search terms',
  'searchToRss.step.previewResults': 'Preview Results',
  'searchToRss.step.previewResults.desc': 'Verify search results',
  'searchToRss.step.feedMetadata': 'Feed Metadata',
  'searchToRss.step.feedMetadata.desc': 'Configure feed details',
  'searchToRss.step.saveRecipe': 'Save Recipe',
  'searchToRss.step.saveRecipe.desc': 'Save as custom recipe',
  'searchToRss.step1.modeLabel': 'Choose search mode',
  'searchToRss.step1.label': 'Search Content',
  'searchToRss.step1.help':
    'Enter the keywords, topic, or question you want to track.',
  'searchToRss.step1.placeholder': "e.g. 'latest AI news' or 'SpaceX launches'",
  'searchToRss.step1.providerTip':
    'Search results use the configured search provider.',
  'searchToRss.step1.button': 'Preview Results',
  'searchToRss.mode.keyword.title': 'Keyword Search',
  'searchToRss.mode.keyword.description':
    'Search exactly what you type. Best for names, products, sites, and specific events.',
  'searchToRss.mode.keyword.badge': 'Simple',
  'searchToRss.mode.keyword.placeholder':
    "e.g. 'OpenAI release' or 'site:example.com RSS'",
  'searchToRss.mode.keyword.help':
    'Enter precise keywords or search operators to track.',
  'searchToRss.mode.semantic.title': 'AI Semantic Search',
  'searchToRss.mode.semantic.description':
    'Let AI expand related queries, merge results, and cover synonyms or adjacent topics.',
  'searchToRss.mode.semantic.badge': 'Broader',
  'searchToRss.mode.semantic.placeholder':
    "e.g. 'recent open-source AI tools worth watching'",
  'searchToRss.mode.semantic.help':
    'Describe the topic naturally. AI will generate multiple search queries and merge results.',
  'searchToRss.step2.alert':
    'Found {count} items. Review them below before proceeding.',
  'searchToRss.step3.alert':
    'Customize how this feed appears in your RSS reader.',
  'searchToRss.step3.feedTitle': 'Feed Title',
  'searchToRss.step3.feedDescription': 'Feed Description',
  'searchToRss.step3.siteLink': 'Site Link',
  'searchToRss.step4.reviewAndSave': 'Review & Save',
  'searchToRss.step4.mode': 'Search Mode',
  'searchToRss.step4.query': 'Query',
  'searchToRss.step4.itemsFound': 'Items Found',
  'searchToRss.step4.recipeId': 'Recipe ID',
  'searchToRss.step4.recipeId.help': 'Unique identifier for this recipe.',
  'searchToRss.step4.internalDescription': 'Internal Description',
  'searchToRss.step4.confirmAndSave': 'Confirm & Save',
  'searchToRss.common.back': 'Back',
  'searchToRss.common.next': 'Next Step',
  'searchToRss.msg.queryRequired': 'Query is required',
  'searchToRss.msg.noResults':
    'No results found, please try a different query.',
  'searchToRss.msg.idRequired': 'Recipe ID is required',
  'searchToRss.msg.saved': 'Recipe saved successfully',
  'searchToRss.default.title': 'Search: {query}',
  'searchToRss.default.description':
    'Search results for "{query}" generated by FeedCraft.',
  'searchToRss.placeholder.recipeId': 'e.g. search-ai-news',
  'searchToRss.placeholder.internalDesc':
    'Notes for yourself about this recipe.',
  'searchToRss.msg.saveFailed': 'Failed to save recipe: {msg}',
};
